In [111]:
!pip install xlrd

Requirement already satisfied: xlrd in C:\Automation\Lib\site-packages (2.0.2)

In [165]:
import pandas as pd

df = pd.read_excel("SaleReport_10_08_24_to_30_06_26.xlsx")
df.head()

df1 = pd.read_excel("Sale_Report_01-04-2021_to_08-08-2024.xls")
df1.head()
# Combine both files
df = pd.concat([df, df1], ignore_index=True)

# Remove duplicate rows
df = df.drop_duplicates()

print("Total Rows:", len(df))

Total Rows: 80011

In [166]:

# Convert Date
df['Date'] = pd.to_datetime(
    df['Date'],
    dayfirst=True
)


# Create Year and Month columns
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
monthly = (
    df.groupby(['Year', 'Month', 'Item Name'], as_index=False)
      .agg(
          Quantity=('Quantity', 'sum'),
          Amount=('Amount', 'sum')
      )
)

print(monthly.shape)
monthly.to_excel("Monthly_Product_Sales.xlsx", index=False)

(13595, 5)

In [167]:
print(monthly.columns.tolist())

['Year', 'Month', 'Item Name', 'Quantity', 'Amount']

In [168]:
print(df['Item Name'].nunique())
print(df['Item Name'].unique())

1461
['Safal (Tropical) 1Ltr' 'Copper Sulphate 1Kg' 'H-Lime (Vanita) 400gm' ...
 'Guwar Chowli Jawari (Mrityunjay) 50gm' 'Biozyme (Biostadt) 100ml'
 'Ignite (Biostadt) 500gm']

In [169]:
print("Total rows:", len(df))

Total rows: 80011

In [170]:
print(df['Month'].unique())
print("Number of months:", df['Month'].nunique())

[ 8  9 10 11 12  1  2  3  4  5  6  7]
Number of months: 12

In [171]:
monthly.head()

   Year  Month                   Item Name  Quantity   Amount
0  2022      9     0-0-50 (Greenfield) 1Kg      36.0   4320.0
1  2022      9    0-52-34 (Greenfield) 1Kg      78.0  12490.0
2  2022      9         00-00-50 (ICL) 25Kg       3.0   9300.0
3  2022      9  00-52-34 (Greenfield) 25Kg       1.0   3550.0
4  2022      9   12-61-00 (Greenfield) 1Kg      23.0   2990.0

In [172]:
monthly.tail()

       Year  Month                    Item Name  Quantity  Amount
13590  2026      6         Z-78 (Indofil) 500gm       9.0  3150.0
13591  2026      6  Z-SILICON (NUTRIXEAL) 500GM       8.0  2520.0
13592  2026      6     Zinc Sulphate (GCCI) 1Kg       7.0  1400.0
13593  2026      6  Zinc Sulphate (Nature) 10Kg       1.0   850.0
13594  2026      6                          mel       1.0     0.0

In [173]:
print(df.shape)
print(df['Item Name'].nunique())
print(df['Item Name'].head(10))

(80011, 23)
1461
0         Safal (Tropical) 1Ltr
1           Copper Sulphate 1Kg
2         H-Lime (Vanita) 400gm
3       Cabrio Top (BASF) 300gm
4             Urea (Kisan) 45Kg
5             Urea (Kisan) 45Kg
6      TAG SAF (Tropical) 115ml
7       TAGTAF (Tropical) 500gm
8         Contaf (Rallis) 250ml
9    Tag Start (Tropical) 100gm
Name: Item Name, dtype: object

In [174]:
print(monthly.shape)
print(monthly['Item Name'].nunique())

(13595, 5)
1461

In [175]:
print(df['Item Code'].isna().sum())
print(df['Item Code'].notna().sum())

79947
64

In [176]:
monthly.head()

   Year  Month                   Item Name  Quantity   Amount
0  2022      9     0-0-50 (Greenfield) 1Kg      36.0   4320.0
1  2022      9    0-52-34 (Greenfield) 1Kg      78.0  12490.0
2  2022      9         00-00-50 (ICL) 25Kg       3.0   9300.0
3  2022      9  00-52-34 (Greenfield) 25Kg       1.0   3550.0
4  2022      9   12-61-00 (Greenfield) 1Kg      23.0   2990.0

monthly['Rolling3'] = (
    monthly.groupby('Item Name')['Quantity']
           .transform(lambda x: x.shift(1).rolling(3).mean())
)

monthly['Rolling6'] = (
    monthly.groupby('Item Name')['Quantity']
           .transform(lambda x: x.shift(1).rolling(6).mean())
)

In [177]:
monthly.fillna(0, inplace=True)

In [178]:
monthly.head()

   Year  Month                   Item Name  Quantity   Amount
0  2022      9     0-0-50 (Greenfield) 1Kg      36.0   4320.0
1  2022      9    0-52-34 (Greenfield) 1Kg      78.0  12490.0
2  2022      9         00-00-50 (ICL) 25Kg       3.0   9300.0
3  2022      9  00-52-34 (Greenfield) 25Kg       1.0   3550.0
4  2022      9   12-61-00 (Greenfield) 1Kg      23.0   2990.0

In [159]:
monthly.tail()

       Year  Month                    Item Name  Quantity  Amount
13590  2026      6         Z-78 (Indofil) 500gm       9.0  3150.0
13591  2026      6  Z-SILICON (NUTRIXEAL) 500GM       8.0  2520.0
13592  2026      6     Zinc Sulphate (GCCI) 1Kg       7.0  1400.0
13593  2026      6  Zinc Sulphate (Nature) 10Kg       1.0   850.0
13594  2026      6                          mel       1.0     0.0

In [179]:
#monthly_40 = monthly[monthly['Quantity']]

print(monthly.shape)
monthly.head()

(13595, 5)

   Year  Month                   Item Name  Quantity   Amount
0  2022      9     0-0-50 (Greenfield) 1Kg      36.0   4320.0
1  2022      9    0-52-34 (Greenfield) 1Kg      78.0  12490.0
2  2022      9         00-00-50 (ICL) 25Kg       3.0   9300.0
3  2022      9  00-52-34 (Greenfield) 25Kg       1.0   3550.0
4  2022      9   12-61-00 (Greenfield) 1Kg      23.0   2990.0

In [180]:
#monthly_40.to_excel("Monthly_Product_Sales_Qty_GT_40.xlsx", index=False)
monthly.to_excel("Monthly_Product_Sales_Qty_GT_full.xlsx", index=False)

In [182]:
monthly.head()
monthly.shape

(13595, 5)

In [183]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

monthly['ProductID'] = le.fit_transform(monthly['Item Name'])

In [184]:
import joblib

joblib.dump(le, "product_encoder.pkl")

['product_encoder.pkl']

In [185]:
X = monthly[
    [
        'ProductID',
        'Year',
        'Month'
    ]
]

y = monthly['Quantity']

In [186]:
train = monthly[monthly['Year'] <= 2025]
test = monthly[monthly['Year'] == 2026]

X_train = train[X.columns]
y_train = train['Quantity']

X_test = test[X.columns]
y_test = test['Quantity']

In [134]:
!pip install catboost

Requirement already satisfied: catboost in C:\Automation\Lib\site-packages (1.2.10)
Requirement already satisfied: graphviz in C:\Automation\Lib\site-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in C:\Automation\Lib\site-packages (from catboost) (3.10.7)
Requirement already satisfied: numpy<3.0,>=1.16.0 in C:\Automation\Lib\site-packages (from catboost) (2.3.4)
Requirement already satisfied: pandas<4.0,>=0.24 in C:\Automation\Lib\site-packages (from catboost) (2.3.3)
Requirement already satisfied: scipy in C:\Automation\Lib\site-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in C:\Automation\Lib\site-packages (from catboost) (6.8.0)
Requirement already satisfied: six in C:\Automation\Lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Automation\Lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Automation\Lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Automation\Lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in C:\Automation\Lib\site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Automation\Lib\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Automation\Lib\site-packages (from matplotlib->catboost) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Automation\Lib\site-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in C:\Automation\Lib\site-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in C:\Automation\Lib\site-packages (from matplotlib->catboost) (12.0.0)
Requirement already satisfied: pyparsing>=3 in C:\Automation\Lib\site-packages (from matplotlib->catboost) (3.2.5)
Requirement already satisfied: narwhals>=1.15.1 in C:\Automation\Lib\site-packages (from plotly->catboost) (2.17.0)

In [187]:
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor

In [188]:
rf = RandomForestRegressor(
    n_estimators=300,
    random_state=42
)

rf.fit(X_train,y_train)

RandomForestRegressor(n_estimators=300, random_state=42)

In [189]:
xgb = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    random_state=42
)

xgb.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)

In [190]:
cat = CatBoostRegressor(verbose=False)

cat.fit(X_train,y_train)

CatBoostRegressor(loss_function='RMSE', verbose=False)

In [192]:
from sklearn.metrics import mean_absolute_error
import numpy as np

models = {
    "RF": rf,
    "XGB": xgb,
    "CAT": cat
}

for name, model in models.items():

    pred = model.predict(X_test)

    mae = mean_absolute_error(y_test,pred)

    rmse = np.sqrt(((y_test-pred)**2).mean())

    print(name,mae,rmse)

RF 6.819630972818312 21.756634968445375
XGB 7.33701744295101 25.78370952934656
CAT 7.331644866379738 21.046207258596702

In [193]:
import joblib

joblib.dump(xgb,"inventory_model.pkl")

['inventory_model.pkl']